# Generated by Django 5.0.4 on 2024-04-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_cherries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, choices=[('action', 'Action'), ('adventure', 'Adventure'), ('animation', 'Animation'), ('comedy', 'Comedy'), ('crime', 'Crime'), ('documentary', 'Documentary'), ('drama', 'Drama'), ('family', 'Family'), ('fantasy', 'Fantasy'), ('history', 'History'), ('horror', 'Horror'), ('music', 'Music'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('science Fiction', 'Science Fiction'), ('tV Movie', 'TV Movie'), ('thriller', 'Thriller'), ('war', 'War'), ('western', 'Western')], max_length=100),
        ),
        migrations.DeleteModel(
            name='CastMember',
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
