# Generated by Django 5.0.4 on 2024-05-02 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_cherries', '0004_movie_runtime_movie_status_movie_tagline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
