# Generated by Django 5.0.4 on 2024-05-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_cherries', '0006_tvshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='cast',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='genre',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='poster_path',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(),
        ),
    ]
