# Generated by Django 5.0.4 on 2024-05-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_cherries', '0007_tvshow_cast_tvshow_genre_tvshow_overview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshow',
            old_name='release_date',
            new_name='first_air_date',
        ),
        migrations.RenameField(
            model_name='tvshow',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='tvshow',
            name='episodes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvshow',
            name='last_air_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='next_air_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='seasons',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
