# Generated by Django 5.0.4 on 2024-05-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_cherries', '0008_rename_release_date_tvshow_first_air_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='id_tvshow',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
