# Generated by Django 5.0.4 on 2024-05-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happy_cherries', '0009_tvshow_id_tvshow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshow',
            old_name='next_air_date',
            new_name='next_episode_to_air',
        ),
        migrations.RenameField(
            model_name='tvshow',
            old_name='episodes',
            new_name='number_of_episodes',
        ),
        migrations.RenameField(
            model_name='tvshow',
            old_name='seasons',
            new_name='number_of_seasons',
        ),
    ]
