# Generated by Django 5.0.4 on 2024-05-08 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_cherries', '0010_rename_next_air_date_tvshow_next_episode_to_air_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tvshow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='happy_cherries.tvshow'),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='happy_cherries.movie'),
        ),
    ]
