# Generated by Django 5.0.4 on 2024-05-14 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_cherries', '0011_review_tvshow_alter_review_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=100)),
                ('tvshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happy_cherries.tvshow')),
            ],
        ),
    ]
