# Generated by Django 5.0.4 on 2024-05-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_cherries', '0012_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
