# Generated by Django 5.0.4 on 2024-06-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_cherries', '0013_note_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='id_movie',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
