# Generated by Django 5.0.4 on 2024-09-12 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_cherries', '0017_rename_name_tvshow_title_note_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Watching', 'Watching'), ('Completed', 'Completed'), ('On-hold', 'On-hold'), ('Dropped', 'Dropped'), ('Plan to watch', 'Plan to watch')], max_length=13)),
                ('episodes_watched', models.IntegerField()),
                ('your_score', models.IntegerField(choices=[(1, 'Appalling'), (2, 'Horrible'), (3, 'Very bad'), (4, 'Bad'), (5, 'Average'), (6, 'Fine'), (7, 'Good'), (8, 'Very Good'), (9, 'Great'), (10, 'Masterpiece')], default=5)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_date_unknown', models.BooleanField(default=False)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('finish_date_unknown', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=6)),
                ('total_times_rewatched', models.IntegerField(default=0)),
                ('rewatch_value', models.CharField(choices=[('Very Low', 'Very Low'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Very High', 'Very High')], max_length=9)),
                ('comment', models.TextField()),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='happy_cherries.movie')),
                ('tvshow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='happy_cherries.tvshow')),
            ],
        ),
    ]
