# Generated by Django 5.0.4 on 2024-09-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_cherries', '0018_extendedreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedreview',
            name='your_score',
            field=models.IntegerField(choices=[(1, 'Appalling (1)'), (2, 'Horrible (2)'), (3, 'Very bad (3)'), (4, 'Bad (4)'), (5, 'Average (5)'), (6, 'Fine (6)'), (7, 'Good (7)'), (8, 'Very Good (8)'), (9, 'Great (9)'), (10, 'Masterpiece (10)')], default=5),
        ),
    ]
