# Generated by Django 5.0.4 on 2024-09-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_cherries', '0019_alter_extendedreview_your_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='next_episode_to_air',
            field=models.DateField(blank=True, null=True),
        ),
    ]
