# Generated by Django 5.0.4 on 2024-09-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_cherries', '0020_alter_tvshow_next_episode_to_air'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='tagline',
            field=models.CharField(default='None', max_length=300),
            preserve_default=False,
        ),
    ]
