# Generated by Django 5.0.4 on 2024-09-18 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_cherries', '0021_tvshow_tagline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedMovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Watching', 'Watching'), ('Completed', 'Completed'), ('On-hold', 'On-hold'), ('Dropped', 'Dropped'), ('Plan to watch', 'Plan to watch')], max_length=13)),
                ('your_score', models.IntegerField(choices=[(1, 'Appalling (1)'), (2, 'Horrible (2)'), (3, 'Very bad (3)'), (4, 'Bad (4)'), (5, 'Average (5)'), (6, 'Fine (6)'), (7, 'Good (7)'), (8, 'Very Good (8)'), (9, 'Great (9)'), (10, 'Masterpiece (10)')], default=5)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=6)),
                ('rewatch_value', models.CharField(choices=[('Very Low', 'Very Low'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Very High', 'Very High')], max_length=9)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('finish_date_unknown', models.BooleanField(default=False)),
                ('total_times_rewatched', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('first_time_watched', models.DateField(blank=True, null=True)),
                ('last_time_watched', models.DateField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happy_cherries.movie')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtendedTvShowReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Watching', 'Watching'), ('Completed', 'Completed'), ('On-hold', 'On-hold'), ('Dropped', 'Dropped'), ('Plan to watch', 'Plan to watch')], max_length=13)),
                ('your_score', models.IntegerField(choices=[(1, 'Appalling (1)'), (2, 'Horrible (2)'), (3, 'Very bad (3)'), (4, 'Bad (4)'), (5, 'Average (5)'), (6, 'Fine (6)'), (7, 'Good (7)'), (8, 'Very Good (8)'), (9, 'Great (9)'), (10, 'Masterpiece (10)')], default=5)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=6)),
                ('rewatch_value', models.CharField(choices=[('Very Low', 'Very Low'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Very High', 'Very High')], max_length=9)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('finish_date_unknown', models.BooleanField(default=False)),
                ('total_times_rewatched', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('episodes_watched', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_date_unknown', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tvshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happy_cherries.tvshow')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ExtendedReview',
        ),
    ]
