# Generated by Django 5.0.4 on 2024-10-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_cherries', '0022_extendedmoviereview_extendedtvshowreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='favorites',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='watchlist',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvshow',
            name='favorites',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvshow',
            name='watchlist',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
