# Generated by Django 5.0.4 on 2024-11-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_cherries', '0023_movie_favorites_movie_watchlist_tvshow_favorites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedmoviereview',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extendedmoviereview',
            name='priority',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='extendedmoviereview',
            name='rewatch_value',
            field=models.CharField(blank=True, choices=[('Very Low', 'Very Low'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Very High', 'Very High')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='extendedmoviereview',
            name='status',
            field=models.CharField(blank=True, choices=[('Watching', 'Watching'), ('Completed', 'Completed'), ('On-hold', 'On-hold'), ('Dropped', 'Dropped'), ('Plan to watch', 'Plan to watch')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='extendedmoviereview',
            name='your_score',
            field=models.IntegerField(blank=True, choices=[(1, 'Appalling (1)'), (2, 'Horrible (2)'), (3, 'Very bad (3)'), (4, 'Bad (4)'), (5, 'Average (5)'), (6, 'Fine (6)'), (7, 'Good (7)'), (8, 'Very Good (8)'), (9, 'Great (9)'), (10, 'Masterpiece (10)')], default=5, null=True),
        ),
        migrations.AlterField(
            model_name='extendedtvshowreview',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extendedtvshowreview',
            name='priority',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='extendedtvshowreview',
            name='rewatch_value',
            field=models.CharField(blank=True, choices=[('Very Low', 'Very Low'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Very High', 'Very High')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='extendedtvshowreview',
            name='status',
            field=models.CharField(blank=True, choices=[('Watching', 'Watching'), ('Completed', 'Completed'), ('On-hold', 'On-hold'), ('Dropped', 'Dropped'), ('Plan to watch', 'Plan to watch')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='extendedtvshowreview',
            name='your_score',
            field=models.IntegerField(blank=True, choices=[(1, 'Appalling (1)'), (2, 'Horrible (2)'), (3, 'Very bad (3)'), (4, 'Bad (4)'), (5, 'Average (5)'), (6, 'Fine (6)'), (7, 'Good (7)'), (8, 'Very Good (8)'), (9, 'Great (9)'), (10, 'Masterpiece (10)')], default=5, null=True),
        ),
    ]
