# Generated by Django 5.0.4 on 2024-11-26 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happy_cherries', '0024_alter_extendedmoviereview_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendedmoviereview',
            name='finish_date_unknown',
        ),
        migrations.RemoveField(
            model_name='extendedtvshowreview',
            name='finish_date_unknown',
        ),
        migrations.RemoveField(
            model_name='extendedtvshowreview',
            name='start_date_unknown',
        ),
    ]
