# Generated by Django 5.0.4 on 2024-12-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_cherries', '0025_remove_extendedmoviereview_finish_date_unknown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedtvshowreview',
            name='episodes_watched',
            field=models.IntegerField(default=0),
        ),
    ]
